# Generated by Django 5.1.1 on 2024-10-16 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=50)),
                ('treinos', models.CharField(max_length=1)),
                ('sessoes', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.CreateModel(
            name='TrainingExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('carga', models.CharField(blank=True, max_length=50, null=True)),
                ('descanso', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.exercicio')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_exercises', to='cadastros.training')),
            ],
            options={
                'verbose_name_plural': 'Training Exercises',
            },
        ),
    ]
