# Generated by Django 5.1.1 on 2024-10-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_exercicio_training_trainingexercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingexercicio',
            name='training',
        ),
        migrations.AlterModelOptions(
            name='trainingexercicio',
            options={},
        ),
        migrations.AddField(
            model_name='trainingexercicio',
            name='descricao',
            field=models.CharField(default='Descrição padrão', max_length=100),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
