# Generated by Django 5.1.1 on 2024-10-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_trainingexercicio_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercicio',
            name='pt',
            field=models.CharField(default='Programa treino', max_length=1),
        ),
    ]
