# Generated by Django 5.1.1 on 2024-10-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_trainingexercicio_pt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingexercicio',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='trainingexercicio',
            name='pt',
        ),
        migrations.AddField(
            model_name='trainingexercicio',
            name='exercises',
            field=models.ManyToManyField(to='cadastros.exercicio'),
        ),
    ]
