# Generated by Django 5.1.1 on 2024-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_remove_exercicio_exercicio_remove_exercicio_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='grupo',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='tipo',
            field=models.CharField(choices=[('Força', 'Força'), ('Cardio', 'Cardio'), ('Flexibilidade', 'Flexibilidade')], default='Força', max_length=50),
        ),
    ]
