# Generated by Django 5.1.1 on 2024-11-28 18:32

import cadastros.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_exercicio_grupo_exercicio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='programa',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='carga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='repeticoes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='series',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='tempo',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='trainingexercicio',
            name='exercicio',
            field=models.ForeignKey(default=cadastros.models.get_default_exercicio, on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='cadastros.exercicio'),
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
