# Generated by Django 5.1.1 on 2024-11-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_remove_exercicio_descricao_remove_exercicio_programa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexercicio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
