# Generated by Django 5.1.1 on 2024-11-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_alter_trainingexercicio_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingexercicio',
            old_name='nome',
            new_name='nome_programa',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='carga',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='repeticoes',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='series',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='trainingexercicio',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='trainingexercicio',
            name='tipo_treino',
        ),
        migrations.AddField(
            model_name='trainingexercicio',
            name='carga',
            field=models.IntegerField(default=0, verbose_name='Carga (kg)'),
        ),
        migrations.AddField(
            model_name='trainingexercicio',
            name='grupo',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingexercicio',
            name='repeticoes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='trainingexercicio',
            name='series',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='trainingexercicio',
            name='tempo',
            field=models.IntegerField(default=0, verbose_name='Minutos (mn)'),
        ),
    ]
