# Generated by Django 5.1.1 on 2024-12-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_trainingexercicio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='nome_completo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
