# Generated by Django 5.1.1 on 2024-11-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(max_length=14, null=True, verbose_name='MATRICULA'),
        ),
    ]
