# Generated by Django 5.1.1 on 2024-11-29 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_programa_treino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='programa_treino',
        ),
    ]
